Bugswriter/tuxi

- tuxi
> forcing english language in curl

- tuxi
The pull request #3 broke the script with posix sh so this one addresses it.
> Removed Bashism

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
This template is opinionated since I saw some issues that contains either brief or unhelpful information. Feel free to close this pr if you don't like it.
> Add bug report issue template

- tuxi
--compressed speeds up the response by 300-1000ms
> --compressed to speed up response

- README.md
Submitting some changes to the README.md focused on improving grammar, style, and readability. Thanks!
> Grammar and style changes for README.md

- tuxi
e.j:
```
$: tuxi "log_2(3) * pi^e"
35.59692278138437
```
> Added support for math operations

- README.md
- tuxi
You can adjust it if it doesn't fit.
<p align="center"><img src="https://user-images.githubusercontent.com/53987136/108081493-9b27f780-70a3-11eb-90a4-c230d25f26c7.png"/></p>
> Better tuxi

- tuxi
Added support for lyrics. This isn't exactly fit for the "Get answers of your questions instantly" description, so I won't mind if this PR gets rejected. 
```
$ tuxi gecgecgec lyrics
---
Back once again
Gec, gec, gec, gec, gec, gec, gec, gec
Gec, gec, gec, gec, gec, gec, gec, gec
Gec, gec, gec, gec, gec, gec, gec, gec
Gec, gec, gec, gec, gec, gec, gec, gec
[...]
```
> Added support for lyrics

- tuxi
I've removed string indexing, made coloring posix-compliant, and removed the non-standard xargs flag.
Testing these changes on OpenBSD, FreeBSD and GNU/Linux. 
This script should also work on MacOS but is untested
> POSIX compatbilitiy changes.

- tuxi
> replaced recode from utf8 to ISO-8859-1

- tuxi
The function to check dependencies would be better with just a loop that checks if every argument is an installed package.
Also, one-liners with `&&` and `||` should be avoided outside of conditionals.
UwU
I use arch btw.
> Human readable

- tuxi
> Getopts, cleaner code?, comments explaining each snippet scraper

- Makefile
- README.md
- tuxi
Doing `make` is much easier than doing `cp tuxi ~/.local/bin`
> Added a makefile

- tuxi
I just made sure that the link pointed to the issues page.
> 📝 switched bugs link

- tuxi
> -r silences Yellow

- README.md
> Read Me: Introduction to tables

- README.md
> Awesome Read Me

- README.md
Sorry for spamming PRs, this is last
@Bugswriter
> Read Me: More useful info about translate

- README.md
- tuxi
> searches for meaning of a word

- tuxi
easier to update when Google Search updates.
> translation scrapper is smaller

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
> added location to bug report

- tuxi
outputs html file to $HOME/.cache/tuxi/
creates $HOME/.cache/tuxi/ if it doesn't exist
html file format: tuxi-\<epoch\>-\<query\>.html
> added -d debug mode

- tuxi
- tuxiqualitytest.sh
-passed all tests
-debug mode from #77 added.
-issue #68 fixed completely
-issues #68 and #74 can now be closed.
> panacea 3 electric boogalo edition

- tuxi
- tuxiqualitytest.sh
This could be improved to make the list look more elegant but trying to `jq` the JSON wasn't a very pleasing experience, so I decided resort to this basic implementation.
```
$ tuxi game of thrones s03 episodes
---
S03 E10 · Mhysa
Jun 9, 2013
S03 E09 · The Rains of Castamere
Jun 2, 2013
S03 E08 · Second Sons
May 19, 2013
S03 E07 · The Bear and the Maiden Fair
May 12, 2013
[...]
```
```
$ tuxi elephant height
---
African bush elephant: 3.2 m
Asian elephant: 2.8 m
---
```
> Added basic support for rich list

- README.md
- tuxi
> Small Readme and Tuxi fixes

- Makefile
- README.md
> Read Me: Installation and update instruction

- tuxi
> fixed debug

- Makefile
- tuxi
Follow up of #98, weather now displays much more information.
> Made weather better.

- tuxiqualitytest.sh
I tried my best to include different ways of how people could possibly format the questions to make sure everything works
> improved and add more tests to quality test

- README.md
- tuxi
People may want to change the language of their queries, this would allow for it to be much easier.
> Language constant

- tuxi
Hippity hoppity, Now your script uses sed fuckery!
xd
> sed fuckery

- tuxi
> PureArtistry version - first commit

- tuxi
added ability to select what snippets to use from the command line and the quotes scrape you mentioned
> Purert version

- tuxi
To test this code, just do
```bash
git clone https://github.com/BeyondMagic/tuxi.git bmtuxi
cd bmtuxi
./tuxi "linus torvalds"
./tuxi ".............."
```
The code was simplified using a function to scrap the HTML, it's very simple.
> Optimized code

- tuxiqualitytest.sh
Added more diverse test cases, now it doesnt just output to a text file, also pops up
> updated test script

- tuxi
This PR is the same as the one in #148, but the branch is set to `main` instead of `develop` in this one.
> added "Learn to pronounce" scraper

- tuxi
- tuxiqualitytest.sh
Lmao half (or like 90%) of this code is pureartistry's. Everything is working, the testoutput is attached. I recommend someone else try and make sure this works before merge. 
<br/>
BTW, this code is supposed to be temporary fix for #112 until purert gets into main, so it should be fine for now.
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6031464/testoutputs.txt)
> implement pureartistry's fix, but for main

- tests/testqueries.txt
- tests/tuxiqualitytest.sh
- tuxi
sorry for the delay with this, got kinda busy...
completely re-worked processing code, no more stupid lock file and no more crashes
added a number of new features and updated help to reflect everything available [ this will fix: #151 #118 #50 implements #137 #87 ]
also re-worked test script making it easier to maintain and makes the output easier to parse (more grep friendly)
priority order may need fiddling with, needs some testing to figure out best order
also the testqueries.txt could do with going through and updating
[testoutputs.txt](https://github.com/Bugswriter/tuxi/files/6056918/testoutputs.txt)
let me know what you think
> big update, see PR for details

- tuxi
can you merge this first please
> updated did you mean

- README.md
- tuxi
Math doesn't result any special characters, only numbers, points and commas. I believe it doesn't change to any language at all, running recode is unnecessary.
> [purert-version] reworked math
